# Terrible code thrown together 30 min before exam
print("Enter choice:")
print("1 Functional form")
print("2 Symmetrical form")
print("3 General form")

choice = int(input())

if choice == 1:
    print("Functional form")
    print("Enter m")
    m = float(input())
    print("Enter b")
    b = float(input())
    print("y=", m, "x + ", b)
    print("Slope ", m)
    print("Y icpt ", b)
    print("X icpt" , -b/m)
    print("Symmetrical form:")
    print("x/", -b/m, "+ y/", b, "= 1")
    print("General form:")
    print(m, "x - y +", b, "= 0")
elif choice == 2:
    print("Symmetrical form")
    print("Enter a")
    a = float(input())
    print("Enter b")
    b = float(input())
    print("x/", a, "+ y/", b, "= 1")
    print("Slope ", -b/a)
    print("Y icpt ", b)
    print("X icpt" , a)
    print("Functional form:")
    print("y=", -b/a, "x + ", b)
    print("General form:")
    print(-b/a, "x - y +", b, "= 0")
elif choice == 3:
    print("General form")
    print("Enter A")
    A = float(input())
    print("Enter B")
    B = float(input())
    print("Enter C")
    C = float(input())
    print(A, "x +", B, "y +", C, "= 0")
    print("Slope ", -A/B)
    print("Y icpt ", -C/B)
    print("X icpt" , -C/A)
    print("Functional form:")
    print("y=", -A/B, "x + ", -C/B)
    print("Symmetrical form:")
    print("x/", -C/A, "+ y/", -C/B, "= 1")
